import { Product } from '../types';

// ============================================
// SWITCHES
// ============================================
export const switchProducts: Product[] = [
  {
    id: "switch-ss30007",
    name: "Push Pull Small (Deluxe) - SS30007",
    slug: "push-pull-small-deluxe-ss30007",
    category: "Switches",
    description: "Push Pull Small Deluxe switch with black cylindrical knob featuring SAROOP logo. Silver ring and threaded shaft with hexagonal black plastic base.",
    partNumber: "SS30007",
    images: ["/products/electrical-components/switches/SS30007.jpg"],
    featured: true,
    specifications: {
      "Type": "Push Pull",
      "Size": "Small",
      "Variant": "Deluxe",
      "Packing": "10 Pcs. Packing",
    },
    tags: ["switch", "push-pull", "small", "deluxe", "automotive"],
    applications: ["Automotive", "Lighting Control"],
  },
  {
    id: "switch-ss30010",
    name: "Push Pull Long (Regular) - SS30010",
    slug: "push-pull-long-regular-ss30010",
    category: "Switches",
    description: "Push Pull Long Regular switch with tall, slender black cylindrical knob featuring SAROOP logo. Silver ring and threaded shaft with hexagonal black plastic base.",
    partNumber: "SS30010",
    images: ["/products/electrical-components/switches/SS30010.jpg"],
    specifications: {
      "Type": "Push Pull",
      "Size": "Long",
      "Variant": "Regular",
      "Packing": "10 Pcs. Packing",
    },
    tags: ["switch", "push-pull", "long", "regular", "automotive"],
    applications: ["Automotive", "Lighting Control"],
  },
  {
    id: "switch-ss30011",
    name: "Push Pull Long (Deluxe) - SS30011",
    slug: "push-pull-long-deluxe-ss30011",
    category: "Switches",
    description: "Push Pull Long Deluxe switch with elongated black cylindrical knob featuring SAROOP logo. Silver ring and threaded shaft with hexagonal black plastic base.",
    partNumber: "SS30011",
    images: ["/products/electrical-components/switches/SS30011.jpg"],
    specifications: {
      "Type": "Push Pull",
      "Size": "Long",
      "Variant": "Deluxe",
      "Packing": "10 Pcs. Packing",
    },
    tags: ["switch", "push-pull", "long", "deluxe", "automotive"],
    applications: ["Automotive", "Lighting Control"],
  },
  {
    id: "switch-ss30014",
    name: "Push Pull Long Big (Nob) - SS30014",
    slug: "push-pull-long-big-nob-ss30014",
    category: "Switches",
    description: "Push Pull Long Big Nob switch with larger, rounded bulbous black knob featuring SAROOP logo. Silver ring and threaded shaft with hexagonal black plastic base.",
    partNumber: "SS30014",
    images: ["/products/electrical-components/switches/SS30014.jpg"],
    specifications: {
      "Type": "Push Pull",
      "Size": "Long Big",
      "Variant": "Nob",
      "Packing": "10 Pcs. Packing",
    },
    tags: ["switch", "push-pull", "long", "big", "nob", "automotive"],
    applications: ["Automotive", "Lighting Control"],
  },
  {
    id: "switch-ss30016",
    name: "Push Pull Long Deluxe (Small Nob) - SS30016",
    slug: "push-pull-long-deluxe-small-nob-ss30016",
    category: "Switches",
    description: "Push Pull Long Deluxe Small Nob switch with very tall and slender black cylindrical knob. Silver ring and threaded shaft with hexagonal black plastic base.",
    partNumber: "SS30016",
    images: ["/products/electrical-components/switches/SS30016.jpg"],
    specifications: {
      "Type": "Push Pull",
      "Size": "Long Deluxe",
      "Variant": "Small Nob",
      "Packing": "10 Pcs. Packing",
    },
    tags: ["switch", "push-pull", "long", "deluxe", "small-nob", "automotive"],
    applications: ["Automotive", "Lighting Control"],
  },
  {
    id: "switch-ss30018",
    name: "Push Pull Extra Long - SS30018",
    slug: "push-pull-extra-long-ss30018",
    category: "Switches",
    description: "Push Pull Extra Long switch with mushroom-shaped black knob on notably long silver threaded shaft. Hexagonal black plastic base.",
    partNumber: "SS30018",
    images: ["/products/electrical-components/switches/SS30018.jpg"],
    specifications: {
      "Type": "Push Pull",
      "Size": "Extra Long",
      "Packing": "10 Pcs. Packing",
    },
    tags: ["switch", "push-pull", "extra-long", "automotive"],
    applications: ["Automotive", "Lighting Control"],
  },
  {
    id: "switch-ss30031",
    name: "Toggle Switch - SS30031",
    slug: "toggle-switch-ss30031",
    category: "Switches",
    description: "Toggle switch with black lever-style design. Black plastic body with silver threaded mounting base and brass screw terminals.",
    partNumber: "SS30031",
    images: ["/products/electrical-components/switches/SS30031.jpg"],
    specifications: {
      "Type": "Toggle",
      "Packing": "10 Pcs. Packing",
    },
    tags: ["switch", "toggle", "automotive"],
    applications: ["Automotive", "General Switching"],
  },
  {
    id: "switch-ss30054",
    name: "Horn Button - SS30054",
    slug: "horn-button-ss30054",
    category: "Switches",
    description: "Horn button with clear/translucent top, ribbed brass body, and black rectangular plastic base with brass screw terminals.",
    partNumber: "SS30054",
    images: ["/products/electrical-components/switches/SS30054.jpg"],
    specifications: {
      "Type": "Push Button",
      "Application": "Horn",
      "Packing": "10 Pcs. Packing",
    },
    tags: ["switch", "horn", "button", "automotive"],
    applications: ["Automotive", "Horn Activation"],
  },
  {
    id: "switch-ss30059",
    name: "Starter/Horn Button Brass Body - SS30059",
    slug: "starter-horn-button-brass-ss30059",
    category: "Switches",
    description: "Heavy-duty starter and horn button with prominent red plastic top, brass body, and black plastic base with three brass screw terminals.",
    partNumber: "SS30059",
    images: ["/products/electrical-components/switches/SS30059.jpg"],
    specifications: {
      "Type": "Push Button",
      "Application": "Starter/Horn",
      "Material": "Brass Body",
      "Packing": "10 Pcs. Packing",
    },
    tags: ["switch", "starter", "horn", "button", "brass", "automotive"],
    applications: ["Automotive", "Starter", "Horn Activation", "Heavy Duty"],
  },
  {
    id: "switch-ss31001",
    name: "Head Light Switch - SS31001",
    slug: "head-light-switch-ss31001",
    category: "Switches",
    description: "Headlight switch with orange cylindrical knob attached to metal shaft. Black rectangular plastic body with multiple brass screw terminals.",
    partNumber: "SS31001",
    images: ["/products/electrical-components/switches/SS31001.jpg"],
    specifications: {
      "Type": "Headlight Switch",
      "Packing": "10 Pcs. Packing",
    },
    tags: ["switch", "headlight", "automotive"],
    applications: ["Automotive", "Headlight Control"],
  },
];

// ============================================
// FLASHERS
// ============================================
export const flasherProducts: Product[] = [
  {
    id: "flasher-1",
    name: "Electronic Flasher 12V",
    slug: "electronic-flasher-12v",
    category: "Flasher",
    description: "Electronic turn signal flasher relay 12V. Compatible with LED and incandescent bulbs.",
    partNumber: "SEF31211",
    image: "/products/electrical-components/electronic-flasher/SEF31211.jpg",
    featured: true,
    specifications: {
      "Type": "Electronic",
      "Voltage": "12V",
      "Compatibility": "LED, Incandescent",
      "Applications": "Turn signals, Hazard lights",
    },
    tags: ["flasher", "electronic", "12v"],
    applications: ["Automotive", "2-Wheeler", "4-Wheeler"],
  },
  {
    id: "flasher-2",
    name: "Electronic Flasher 24V",
    slug: "electronic-flasher-24v",
    category: "Flasher",
    description: "Electronic turn signal flasher relay 24V for commercial vehicles.",
    partNumber: "SEF32411",
    image: "/products/electrical-components/electronic-flasher/SEF32411.jpg",
    specifications: {
      "Type": "Electronic",
      "Voltage": "24V",
      "Compatibility": "LED, Incandescent",
      "Applications": "Turn signals, Hazard lights",
    },
    tags: ["flasher", "electronic", "24v"],
    applications: ["Commercial Vehicles"],
  },
  {
    id: "flasher-3",
    name: "Musical Flasher 12V",
    slug: "musical-flasher-12v",
    category: "Flasher",
    description: "Musical flasher with melody feature for turn signal indication 12V.",
    partNumber: "SMF31202",
    image: "/products/electrical-components/musical-flasher/SMF31202.jpg",
    specifications: {
      "Type": "Musical/Melody",
      "Voltage": "12V",
      "Feature": "Audio indication",
      "Applications": "Turn signals",
    },
    tags: ["flasher", "musical", "12v"],
    applications: ["Automotive"],
  },
  {
    id: "flasher-4",
    name: "Musical Flasher 24V",
    slug: "musical-flasher-24v",
    category: "Flasher",
    description: "Musical flasher with melody feature for turn signal indication 24V.",
    partNumber: "SMF32402",
    image: "/products/electrical-components/musical-flasher/SMF32402.jpg",
    specifications: {
      "Type": "Musical/Melody",
      "Voltage": "24V",
      "Feature": "Audio indication",
      "Applications": "Turn signals",
    },
    tags: ["flasher", "musical", "24v"],
    applications: ["Commercial Vehicles"],
  },
];

// ============================================
// RELAYS
// ============================================
export const relayProducts: Product[] = [
  {
    id: "relay-1",
    name: "2 Wheeler Relay",
    slug: "2-wheeler-relay",
    category: "Relay",
    subcategory: "2 Wheeler",
    description: "Relay designed for two-wheeler motorcycles and scooters. 4 Pin 12V.",
    specifications: {
      "Compatible": "2 Wheelers",
      "Voltage": "12V",
      "Pins": "4",
    },
    tags: ["relay", "2-wheeler"],
    applications: ["Motorcycles", "Scooters"],
  },
  {
    id: "relay-2",
    name: "Starting Relay 12V",
    slug: "starting-relay-12v",
    category: "Relay",
    subcategory: "Starting Relay",
    description: "Starter motor relay for vehicle ignition systems. Suitable for 2 & 4 Wheeler.",
    partNumber: "S2WR21201",
    image: "/products/electrical-components/2wheeler-relay/S2WR21201.jpg",
    specifications: {
      "Type": "Starter Relay",
      "Voltage": "12V",
      "Applications": "Ignition system",
    },
    tags: ["relay", "starting", "12v"],
    applications: ["Automotive", "Starting System"],
  },
  {
    id: "relay-3",
    name: "4 Wheeler Relay 12V",
    slug: "4-wheeler-relay-12v",
    category: "Relay",
    subcategory: "4 Wheeler",
    description: "Relay designed for four-wheeler cars and SUVs. 4 Pin 12V.",
    featured: true,
    specifications: {
      "Compatible": "4 Wheelers",
      "Voltage": "12V",
      "Pins": "4",
    },
    tags: ["relay", "4-wheeler", "12v"],
    applications: ["Cars", "SUVs"],
  },
  {
    id: "relay-4",
    name: "4 Wheeler Relay 24V",
    slug: "4-wheeler-relay-24v",
    category: "Relay",
    subcategory: "4 Wheeler",
    description: "Relay designed for commercial vehicles. 4 Pin 24V.",
    specifications: {
      "Compatible": "Commercial Vehicles",
      "Voltage": "24V",
      "Pins": "4",
    },
    tags: ["relay", "4-wheeler", "24v"],
    applications: ["Commercial Vehicles"],
  },
  {
    id: "relay-5",
    name: "Head Light Relay 12V",
    slug: "headlight-relay-12v",
    category: "Relay",
    subcategory: "Headlight Relay",
    description: "High-power relay for headlight circuits. Improves light output and protects switch. 6 Pin with wire.",
    partNumber: "SR61201",
    image: "/products/electrical-components/headlight-relay/SR61201.jpg",
    featured: true,
    specifications: {
      "Type": "Headlight Relay",
      "Voltage": "12V",
      "Rating": "30A/40A",
      "Pins": "6",
      "Applications": "Headlight upgrade",
    },
    tags: ["relay", "headlight", "12v"],
    applications: ["Automotive", "Lighting"],
  },
  {
    id: "relay-6",
    name: "Head Light Relay 24V",
    slug: "headlight-relay-24v",
    category: "Relay",
    subcategory: "Headlight Relay",
    description: "High-power relay for headlight circuits in commercial vehicles. 6 Pin with wire.",
    partNumber: "SR62401",
    image: "/products/electrical-components/headlight-relay/SR62401.jpg",
    specifications: {
      "Type": "Headlight Relay",
      "Voltage": "24V",
      "Rating": "30A/40A",
      "Pins": "6",
      "Applications": "Headlight upgrade",
    },
    tags: ["relay", "headlight", "24v"],
    applications: ["Commercial Vehicles", "Lighting"],
  },
  {
    id: "relay-7",
    name: "Horn Relay 3 Pin 12V",
    slug: "horn-relay-3pin-12v",
    category: "Relay",
    subcategory: "Horn Relay",
    description: "Horn relay with 3 pin configuration for 12V systems.",
    partNumber: "SR31201",
    image: "/products/electrical-components/horn-relay/SR31201.jpg",
    specifications: {
      "Type": "Horn Relay",
      "Voltage": "12V",
      "Pins": "3",
      "Applications": "Horn circuits",
    },
    tags: ["relay", "horn", "12v"],
    applications: ["Automotive"],
  },
  {
    id: "relay-8",
    name: "5 Pin Micro Relay 12V",
    slug: "5-pin-micro-relay-12v",
    category: "Relay",
    subcategory: "Micro Relay",
    description: "Compact 5 pin micro relay for 12V automotive applications.",
    partNumber: "SR51201",
    image: "/products/electrical-components/relay/SR51201.jpg",
    specifications: {
      "Type": "Micro Relay",
      "Voltage": "12V",
      "Pins": "5",
    },
    tags: ["relay", "micro", "12v"],
    applications: ["Automotive"],
  },
  {
    id: "relay-9",
    name: "5 Pin Micro Relay 24V",
    slug: "5-pin-micro-relay-24v",
    category: "Relay",
    subcategory: "Micro Relay",
    description: "Compact 5 pin micro relay for 24V commercial vehicle applications.",
    partNumber: "SR52401",
    image: "/products/electrical-components/relay/SR52401.jpg",
    specifications: {
      "Type": "Micro Relay",
      "Voltage": "24V",
      "Pins": "5",
    },
    tags: ["relay", "micro", "24v"],
    applications: ["Commercial Vehicles"],
  },
  {
    id: "relay-10",
    name: "Mini Relay 4 Pin 12V",
    slug: "mini-relay-4pin-12v",
    category: "Relay",
    subcategory: "Mini Relay",
    description: "Compact mini relay with 4 pin configuration for 12V systems.",
    specifications: {
      "Type": "Mini Relay",
      "Voltage": "12V",
      "Pins": "4",
    },
    tags: ["relay", "mini", "12v"],
    applications: ["Automotive"],
  },
  {
    id: "relay-11",
    name: "Transparent Relay 4 Pin 12V",
    slug: "transparent-relay-4pin-12v",
    category: "Relay",
    subcategory: "Transparent Relay",
    description: "Transparent housing relay for easy fault diagnosis. 4 Pin 12V.",
    specifications: {
      "Type": "Transparent",
      "Voltage": "12V",
      "Pins": "4",
    },
    tags: ["relay", "transparent", "12v"],
    applications: ["Automotive"],
  },
];

// ============================================
// TUNERS
// ============================================
export const tunerProducts: Product[] = [
  {
    id: "tuner-1",
    name: "4 Way Tuner",
    slug: "4-way-tuner",
    category: "Tuner",
    description: "4-way electrical distribution tuner for vehicle wiring.",
    specifications: {
      "Ways": "4",
      "Applications": "Electrical distribution",
    },
    tags: ["tuner", "4-way", "distribution"],
    applications: ["Automotive", "Electrical Distribution"],
  },
  {
    id: "tuner-2",
    name: "7 Way Tuner",
    slug: "7-way-tuner",
    category: "Tuner",
    description: "7-way electrical distribution tuner.",
    specifications: {
      "Ways": "7",
      "Applications": "Electrical distribution",
    },
    tags: ["tuner", "7-way"],
    applications: ["Automotive", "Electrical Distribution"],
  },
  {
    id: "tuner-3",
    name: "8 Way Tuner",
    slug: "8-way-tuner",
    category: "Tuner",
    description: "8-way electrical distribution tuner.",
    specifications: {
      "Ways": "8",
      "Applications": "Electrical distribution",
    },
    tags: ["tuner", "8-way"],
    applications: ["Automotive", "Electrical Distribution"],
  },
];
